import { Injectable } from "@angular/core";
import { InMemoryDbService } from "angular-in-memory-web-api";
import { Category } from "../../models/category";

@Injectable({
  providedIn: "root",
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const categories = [
      {
        pk: 1,
        name: "Basics",
        description: "Basics",
        parent: null,
        numQues: 5,
        avgSuccess: 100.0,
      },
      {
        pk: 2,
        name: "Variables",
        description: "Variables",
        parent: 1,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 3,
        name: "Statements",
        description: "Statements",
        parent: 1,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 4,
        name: "Data Types",
        description: "Data Types",
        parent: 1,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 5,
        name: "Constants",
        description: "Constants",
        parent: 1,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 6,
        name: "Casting",
        description: "Casting",
        parent: 1,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 7,
        name: "Arithmetic Operators",
        description: "Arithmetic Operators",
        parent: 1,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 8,
        name: "Simple Calculation Programs",
        description: "Simple Calculation Programs",
        parent: 1,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 9,
        name: "Pre-Defined Classes",
        description: "Pre-Defined Classes",
        parent: null,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 10,
        name: "OOP Overview",
        description: "OOP Overview",
        parent: 9,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 11,
        name: "Scanner",
        description: "Scanner",
        parent: 9,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 12,
        name: "Random",
        description: "Random",
        parent: 9,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 13,
        name: "Math",
        description: "Math",
        parent: 9,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 14,
        name: "Character",
        description: "Character",
        parent: 9,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 15,
        name: "String",
        description: "String",
        parent: 9,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 16,
        name: "Programs with Changing Behaviours",
        description: "Programs with Changing Behaviours",
        parent: 9,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 17,
        name: "Mathematical Programs",
        description: "Mathematical Programs",
        parent: 9,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 18,
        name: "Programs Taking Sentence User Input",
        description: "Programs Taking Sentence User Input",
        parent: 9,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 19,
        name: "Simple Programs Taking Numeric User Input",
        description: "Simple Programs Taking Numeric User Input",
        parent: 9,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 20,
        name: "Conditionals",
        description: "Conditionals",
        parent: null,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 21,
        name: "Boolean Expressions",
        description: "Boolean Expressions",
        parent: 20,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 22,
        name: "Relational and Logical Operators",
        description: "Relational and Logical Operators",
        parent: 20,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 23,
        name: "Decision Diagrams",
        description: "Decision Diagrams",
        parent: 20,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 24,
        name: "Conditional Statements",
        description: "Conditional Statements",
        parent: 20,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 25,
        name: "Simple Programs With Decision Points",
        description: "Simple Programs With Decision Points",
        parent: 20,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 26,
        name: "Nested Conditional Statements",
        description: "Nested Conditional Statements",
        parent: 20,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 27,
        name: "Programs With Decision Points",
        description: "Programs With Decision Points",
        parent: 20,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 28,
        name: "Loops",
        description: "Loops",
        parent: null,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 29,
        name: "Identifying Repetition",
        description: "Identifying Repetition",
        parent: 28,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 30,
        name: "Decision Diagrams",
        description: "Decision Diagrams",
        parent: 28,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 31,
        name: "Variable Scope",
        description: "Variable Scope",
        parent: 28,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 32,
        name: "For Loops",
        description: "For Loops",
        parent: 28,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 33,
        name: "While Loops",
        description: "While Loops",
        parent: 28,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 34,
        name: "Nested Loops",
        description: "Nested Loops",
        parent: 28,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 35,
        name: "Simple Programs With Repetition",
        description: "Simple Programs With Repetition",
        parent: 28,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 36,
        name: "Programs With Repetition",
        description: "Programs With Repetition",
        parent: 28,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 37,
        name: "Methods",
        description: "Methods",
        parent: null,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 38,
        name: "Information Hiding and Abstraction",
        description: "Information Hiding and Abstraction",
        parent: 37,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 39,
        name: "Using Methods",
        description: "Using Methods",
        parent: 37,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 40,
        name: "Defining Methods",
        description: "Defining Methods",
        parent: 37,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 41,
        name: "Variable Scope",
        description: "Variable Scope",
        parent: 37,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 42,
        name: "Method Overloading",
        description: "Method Overloading",
        parent: 37,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 43,
        name: "Modular Programs",
        description: "Modular Programs",
        parent: 37,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 44,
        name: "Arrays",
        description: "Arrays",
        parent: null,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 45,
        name: "Data Representation",
        description: "Data Representation",
        parent: 44,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 46,
        name: "Defining Arrays",
        description: "Defining Arrays",
        parent: 44,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 47,
        name: "Referencing Array and Its Elements",
        description: "Referencing Array and Its Elements",
        parent: 44,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 48,
        name: "Multidimensional Arrays",
        description: "Multidimensional Arrays",
        parent: 44,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 49,
        name: "Arrays with Methods",
        description: "Arrays with Methods",
        parent: 44,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 50,
        name: "Programs Involving Data Sequences",
        description: "Programs Involving Data Sequences",
        parent: 44,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 51,
        name: "Programs Involving Multidimensional Data",
        description: "Programs Involving Multidimensional Data",
        parent: 44,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 52,
        name: "Object Oriented Programming",
        description: "Object Oriented Programming",
        parent: null,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 53,
        name: "OOP Overview",
        description: "OOP Overview",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 54,
        name: "User Defined Classes",
        description: "User Defined Classes",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 55,
        name: "Variable Scope",
        description: "Variable Scope",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 56,
        name: "The Static Modifier",
        description: "The Static Modifier",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 57,
        name: "Programs with Multiple Classes",
        description: "Programs with Multiple Classes",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 58,
        name: "Special Class Method",
        description: "Special Class Method",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 59,
        name: "Simple Programs With User Defined Classes",
        description: "Simple Programs With User Defined Classes",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 60,
        name: "Programs With Interesting Classes",
        description: "Programs With Interesting Classes",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 61,
        name: "Creating Objects From Classes",
        description: "Creating Objects From Classes",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 62,
        name: "Object Independence",
        description: "Object Independence",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
      {
        pk: 63,
        name: "Object Interactions",
        description: "Object Interactions",
        parent: 52,
        numQues: 0,
        avgSuccess: 0,
      },
    ];
    return { categories };
  }

  constructor() {}
}
